name: ludo_flutter
description: Offline board games, starting with Ludo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.6
  provider: ^6.1.2
  shared_preferences: ^2.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
